FROM java:8
EXPOSE 7078
ADD /target/currencyapijenkins-0.0.1-SNAPSHOT.jar /home/eswaribala/currencyapijenkins-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/home/eswaribala/currencyapijenkins-0.0.1-SNAPSHOT.jar"]
